// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGOFPhRa7qb-sacy4WPgAPm_QbDCO-SDE',
    appId: '1:934127375636:web:8f377566496b879eff1e01',
    messagingSenderId: '934127375636',
    projectId: 'aeda-32a41',
    authDomain: 'aeda-32a41.firebaseapp.com',
    storageBucket: 'aeda-32a41.appspot.com',
    measurementId: 'G-H4CF0G6F47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZjgRf1h3DZK5rrQihioVhLpStVD9c2QM',
    appId: '1:934127375636:android:97aba4802c7a3468ff1e01',
    messagingSenderId: '934127375636',
    projectId: 'aeda-32a41',
    storageBucket: 'aeda-32a41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRAVs_3l6338EhmguusikR-4aZvXRqG7M',
    appId: '1:934127375636:ios:062283a1dd94dc53ff1e01',
    messagingSenderId: '934127375636',
    projectId: 'aeda-32a41',
    storageBucket: 'aeda-32a41.appspot.com',
    iosBundleId: 'com.example.aeda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRAVs_3l6338EhmguusikR-4aZvXRqG7M',
    appId: '1:934127375636:ios:ee436ccc86194478ff1e01',
    messagingSenderId: '934127375636',
    projectId: 'aeda-32a41',
    storageBucket: 'aeda-32a41.appspot.com',
    iosBundleId: 'com.example.aeda.RunnerTests',
  );
}
